# DbaClientX bootstrapper
# Auto-generated by PowerForge. Do not edit.

$PowerForgeDevelopmentBinaryLoaded = $false
# Source development binary loader
$PowerForgeDevelopmentBinaryRoot = [IO.Path]::GetFullPath([IO.Path]::Combine($PSScriptRoot, 'DbaClientX.PowerShell', 'bin'))
$PowerForgeDevelopmentBinaryMode = 'Environment'
$PowerForgeDevelopmentBinaryEnvironmentVariable = 'DBACLIENTX_USE_DEVELOPMENT_BINARIES'
$PowerForgeDevelopmentConfigurationEnvironmentVariable = 'DBACLIENTX_DEVELOPMENT_CONFIGURATION'
$PowerForgeDevelopmentCoreFrameworks = @('net8.0', 'net472')
$PowerForgeDevelopmentDesktopFrameworks = @('net472', 'net8.0')
$PowerForgeDevelopmentUseAssemblyLoadContext = $true
$PowerForgeDevelopmentEnabled = $false
if ($PowerForgeDevelopmentBinaryMode -eq 'Auto') {
    $PowerForgeDevelopmentEnabled = $true
} elseif ($PowerForgeDevelopmentBinaryMode -eq 'Environment') {
    $PowerForgeDevelopmentRequestedValue = [Environment]::GetEnvironmentVariable($PowerForgeDevelopmentBinaryEnvironmentVariable)
    $PowerForgeDevelopmentEnabled = [string]::Equals($PowerForgeDevelopmentRequestedValue, 'true', [StringComparison]::OrdinalIgnoreCase)
}

if ($PowerForgeDevelopmentEnabled) {
    $PowerForgeDevelopmentConfigurations = @()
    $PowerForgeDevelopmentRequestedConfiguration = [Environment]::GetEnvironmentVariable($PowerForgeDevelopmentConfigurationEnvironmentVariable)
    if (-not [string]::IsNullOrWhiteSpace($PowerForgeDevelopmentRequestedConfiguration)) {
        $PowerForgeDevelopmentConfigurations += $PowerForgeDevelopmentRequestedConfiguration
    }
    $PowerForgeDevelopmentConfigurations += 'Debug'
    $PowerForgeDevelopmentConfigurations += 'Release'
    $PowerForgeDevelopmentConfigurations = @($PowerForgeDevelopmentConfigurations | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)

    $PowerForgeDevelopmentFrameworks = if ($PSEdition -eq 'Core') { $PowerForgeDevelopmentCoreFrameworks } else { $PowerForgeDevelopmentDesktopFrameworks }
    $PowerForgeDevelopmentBinaryPath = $null
    foreach ($PowerForgeDevelopmentConfiguration in $PowerForgeDevelopmentConfigurations) {
        foreach ($PowerForgeDevelopmentFramework in $PowerForgeDevelopmentFrameworks) {
            $PowerForgeDevelopmentCandidate = [IO.Path]::Combine($PowerForgeDevelopmentBinaryRoot, $PowerForgeDevelopmentConfiguration, $PowerForgeDevelopmentFramework, 'DBAClientX.PowerShell.dll')
            if (Test-Path -LiteralPath $PowerForgeDevelopmentCandidate) {
                $PowerForgeDevelopmentBinaryPath = $PowerForgeDevelopmentCandidate
                break
            }
        }
        if ($PowerForgeDevelopmentBinaryPath) { break }
    }

    if ($PowerForgeDevelopmentBinaryPath) {
        try {
            $ImportModule = Get-Command -Name Import-Module -Module Microsoft.PowerShell.Core
            # Ensure native runtime libraries are discoverable for the selected development binary.
            $PowerForgeDevelopmentIsWindowsPlatform = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)
            if ($PowerForgeDevelopmentIsWindowsPlatform) {
                $PowerForgeDevelopmentArch = [System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture
                $PowerForgeDevelopmentArchFolder = switch ($PowerForgeDevelopmentArch) {
                    'X64' { 'win-x64' }
                    'X86' { 'win-x86' }
                    'Arm64' { 'win-arm64' }
                    'Arm' { 'win-arm' }
                    default {
                        Write-Warning -Message ("Unknown Windows architecture '{0}'. Falling back to win-x64 native runtime probing." -f $PowerForgeDevelopmentArch)
                        'win-x64'
                    }
                }
                $PowerForgeDevelopmentLibFolder = [IO.Path]::GetDirectoryName($PowerForgeDevelopmentBinaryPath)
                if ($PowerForgeDevelopmentLibFolder) {
                    $PowerForgeDevelopmentNativePath = Join-Path -Path $PowerForgeDevelopmentLibFolder -ChildPath ("runtimes\{0}\native" -f $PowerForgeDevelopmentArchFolder)
                    $PowerForgeDevelopmentPathEntries = if ([string]::IsNullOrWhiteSpace($env:PATH)) { @() } else { @($env:PATH -split [IO.Path]::PathSeparator) }
                    if ((Test-Path -LiteralPath $PowerForgeDevelopmentNativePath) -and ($PowerForgeDevelopmentPathEntries -notcontains $PowerForgeDevelopmentNativePath)) {
                        if ([string]::IsNullOrWhiteSpace($env:PATH)) {
                            $env:PATH = $PowerForgeDevelopmentNativePath
                        } else {
                            $env:PATH = "$PowerForgeDevelopmentNativePath$([IO.Path]::PathSeparator)$env:PATH"
                        }
                    }
                }
            }
            if ($PSEdition -eq 'Core' -and $PowerForgeDevelopmentUseAssemblyLoadContext) {
                if (-not ('DbaClientX.DevelopmentModuleLoadContext.ModuleAssemblyLoadContext' -as [type])) {
                    Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;

namespace DbaClientX.DevelopmentModuleLoadContext
{
    public sealed class ModuleAssemblyLoadContext : AssemblyLoadContext
    {
        private static readonly object Sync = new object();
        private static readonly Dictionary<string, ModuleAssemblyLoadContext> Contexts = new Dictionary<string, ModuleAssemblyLoadContext>(StringComparer.OrdinalIgnoreCase);

        private readonly string _assemblyDirectory;
        private readonly string _moduleAssemblyPath;
        private readonly AssemblyDependencyResolver _resolver;
        private Assembly _moduleAssembly;

        private ModuleAssemblyLoadContext(string moduleAssemblyPath, string contextName)
            : base(contextName, isCollectible: false)
        {
            _moduleAssemblyPath = Path.GetFullPath(moduleAssemblyPath);
            _assemblyDirectory = Path.GetDirectoryName(_moduleAssemblyPath) ?? string.Empty;
            _resolver = TryCreateResolver(_moduleAssemblyPath);
        }

        public static Assembly LoadModule(string moduleAssemblyPath, string contextName)
        {
            if (string.IsNullOrWhiteSpace(moduleAssemblyPath))
                throw new ArgumentException("Module assembly path is required.", nameof(moduleAssemblyPath));

            var fullPath = Path.GetFullPath(moduleAssemblyPath);
            if (!File.Exists(fullPath))
                throw new FileNotFoundException("Module assembly was not found.", fullPath);

            lock (Sync)
            {
                ModuleAssemblyLoadContext context;
                if (!Contexts.TryGetValue(fullPath, out context))
                {
                    context = new ModuleAssemblyLoadContext(fullPath, string.IsNullOrWhiteSpace(contextName) ? Path.GetFileNameWithoutExtension(fullPath) : contextName);
                    Contexts[fullPath] = context;
                }

                return context.LoadMainModule();
            }
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            if (assemblyName == null || string.IsNullOrWhiteSpace(assemblyName.Name))
                return null;

            var loaderAssembly = typeof(ModuleAssemblyLoadContext).Assembly.GetName();
            if (AssemblyName.ReferenceMatchesDefinition(loaderAssembly, assemblyName))
                return typeof(ModuleAssemblyLoadContext).Assembly;

            var resolvedPath = _resolver?.ResolveAssemblyToPath(assemblyName);
            if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                return LoadFromAssemblyPath(resolvedPath);

            var assemblyPath = Path.Combine(_assemblyDirectory, assemblyName.Name + ".dll");
            return File.Exists(assemblyPath) ? LoadFromAssemblyPath(assemblyPath) : null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            var resolvedPath = _resolver?.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                return LoadUnmanagedDllFromPath(resolvedPath);

            return IntPtr.Zero;
        }

        private static AssemblyDependencyResolver TryCreateResolver(string assemblyPath)
        {
            try
            {
                return new AssemblyDependencyResolver(assemblyPath);
            }
            catch (InvalidOperationException)
            {
                return null;
            }
        }

        private Assembly LoadMainModule()
        {
            if (_moduleAssembly == null)
                _moduleAssembly = LoadFromAssemblyPath(_moduleAssemblyPath);

            return _moduleAssembly;
        }
    }
}
'@ -Language CSharp -ErrorAction Stop
                }
                $PowerForgeDevelopmentModuleAssembly = [DbaClientX.DevelopmentModuleLoadContext.ModuleAssemblyLoadContext]::LoadModule($PowerForgeDevelopmentBinaryPath, 'DbaClientX.Development')
                $PowerForgeDevelopmentInnerModule = & $ImportModule -Assembly $PowerForgeDevelopmentModuleAssembly -Force -PassThru -ErrorAction Stop
                $ModuleAssembly = $PowerForgeDevelopmentModuleAssembly
                $LibFolder = [IO.Path]::GetDirectoryName($PowerForgeDevelopmentBinaryPath)
                # Type accelerator registration relies on $ModuleAssembly and $LibFolder from this ALC loader scope.
                $RegisterPowerForgeAssemblyTypeAccelerators = {
                    param(
                        [Parameter(Mandatory = $true)][System.Reflection.Assembly] $ModuleAssembly,
                        [Parameter(Mandatory = $true)][string] $LibFolder
                    )

                    $Mode = 'Assembly'
                    $RequestedTypes = @()
                    $RequestedAssemblies = @('DbaClientX.Core', 'DbaClientX.SqlServer', 'DbaClientX.MySql', 'DbaClientX.Oracle', 'DbaClientX.PostgreSql', 'DbaClientX.SQLite', 'DBAClientX.PowerShell')

                    if ($null -eq $ModuleAssembly) {
                        Write-Warning -Message 'Module assembly was not available. ALC dependency type exposure is disabled.'
                        return
                    }

                    if ([string]::IsNullOrWhiteSpace($LibFolder)) {
                        Write-Warning -Message 'Module library folder was not available. ALC dependency type exposure is disabled.'
                        return
                    }

                    $PowerForgeAlcLibraryDirectory = $null
                    if ([IO.Path]::IsPathRooted($LibFolder)) {
                        $PowerForgeAlcLibraryDirectory = [IO.Path]::GetFullPath($LibFolder)
                    } elseif ($LibFolder.Contains('..') -or $LibFolder.IndexOfAny([IO.Path]::GetInvalidFileNameChars()) -ge 0) {
                        Write-Warning -Message "Module library folder '$LibFolder' must be a simple folder name or a rooted development binary directory. ALC dependency type exposure is disabled."
                        return
                    } else {
                        $PowerForgeAlcLibraryDirectory = [IO.Path]::Combine($PSScriptRoot, 'Lib', $LibFolder)
                    }

                    if ($Mode -eq 'AllowList' -and $RequestedTypes.Count -eq 0) {
                        Write-Warning -Message 'AllowList type accelerator mode was configured without type names. No ALC dependency type accelerators will be registered.'
                        return
                    }

                    if ($Mode -eq 'Assembly' -and $RequestedAssemblies.Count -eq 0) {
                        if ($RequestedTypes.Count -eq 0) {
                            Write-Warning -Message 'Assembly type accelerator mode was configured without assembly names or type names. No ALC dependency type accelerators will be registered.'
                            return
                        }

                        Write-Warning -Message 'Assembly type accelerator mode was configured without assembly names. Only explicitly configured type names will be registered.'
                    }

                    $TypeAccelerators = [psobject].Assembly.GetType('System.Management.Automation.TypeAccelerators')
                    if ($null -eq $TypeAccelerators) {
                        Write-Warning -Message 'PowerShell type accelerator APIs are not available. ALC dependency type exposure is disabled.'
                        return
                    }

                    $AddTypeAccelerator = $TypeAccelerators.GetMethod('Add', [type[]]@([string], [type]))
                    $GetTypeAccelerators = $TypeAccelerators.GetProperty('Get', [System.Reflection.BindingFlags] 'Static,Public,NonPublic')
                    if ($null -eq $AddTypeAccelerator -or $null -eq $GetTypeAccelerators) {
                        Write-Warning -Message 'PowerShell type accelerator APIs are incomplete. ALC dependency type exposure is disabled.'
                        return
                    }

                    $ModuleAlc = [System.Runtime.Loader.AssemblyLoadContext]::GetLoadContext($ModuleAssembly)
                    if ($null -eq $ModuleAlc) {
                        Write-Warning -Message 'Unable to resolve the module AssemblyLoadContext. ALC dependency type exposure is disabled.'
                        return
                    }

                    if ($null -eq $script:PowerForgeRegisteredAssemblyTypeAccelerators) {
                        $script:PowerForgeRegisteredAssemblyTypeAccelerators = @{}
                    }

                    $ImportPowerForgeAlcAssembly = {
                        param([Parameter(Mandatory = $true)][string] $AssemblyName)

                        foreach ($Assembly in $ModuleAlc.Assemblies) {
                            if ($Assembly.GetName().Name -eq $AssemblyName) {
                                return $Assembly
                            }
                        }

                        try {
                            return $ModuleAlc.LoadFromAssemblyName([System.Reflection.AssemblyName]::new($AssemblyName))
                        } catch {
                            $AssemblyPath = [IO.Path]::Combine($PowerForgeAlcLibraryDirectory, $AssemblyName + '.dll')
                            if (Test-Path -LiteralPath $AssemblyPath) {
                                try {
                                    $AssemblyNameObject = [System.Reflection.AssemblyName]::GetAssemblyName($AssemblyPath)
                                    return $ModuleAlc.LoadFromAssemblyName($AssemblyNameObject)
                                } catch {
                                    Write-Warning -Message "Could not load ALC assembly '$AssemblyName' for type accelerator exposure: $($_.Exception.Message)"
                                }
                            }
                        }

                        return $null
                    }

                    $FindPowerForgeAlcType = {
                        param([Parameter(Mandatory = $true)][string] $TypeName)

                        foreach ($Assembly in $ModuleAlc.Assemblies) {
                            $Type = $Assembly.GetType($TypeName, $false, $false)
                            if ($null -ne $Type) {
                                return $Type
                            }
                        }

                        $LibDirectory = $PowerForgeAlcLibraryDirectory
                        if (-not (Test-Path -LiteralPath $LibDirectory)) {
                            return $null
                        }

                        foreach ($File in Get-ChildItem -LiteralPath $LibDirectory -Filter '*.dll' -File -ErrorAction SilentlyContinue) {
                            try {
                                $AssemblyName = [System.Reflection.AssemblyName]::GetAssemblyName($File.FullName)
                                $Assembly = & $ImportPowerForgeAlcAssembly -AssemblyName $AssemblyName.Name
                                if ($null -eq $Assembly) {
                                    continue
                                }

                                $Type = $Assembly.GetType($TypeName, $false, $false)
                                if ($null -ne $Type) {
                                    return $Type
                                }
                            } catch {
                                continue
                            }
                        }

                        return $null
                    }

                    $AddPowerForgeTypeAccelerator = {
                        param([Parameter(Mandatory = $true)][type] $Type)

                        if ([string]::IsNullOrWhiteSpace($Type.FullName)) {
                            return
                        }

                        $Name = $Type.FullName
                        $Existing = $GetTypeAccelerators.GetValue($null)
                        if ($Existing.ContainsKey($Name)) {
                            if ([object]::ReferenceEquals($Existing[$Name], $Type)) {
                                return
                            } else {
                                Write-Warning -Message "Type accelerator '$Name' already exists. Keeping the existing accelerator and skipping the ALC type from $($Type.Assembly.GetName().Name)."
                            }
                            return
                        }

                        try {
                            $AddTypeAccelerator.Invoke($null, @($Name, $Type)) | Out-Null
                        } catch {
                            Write-Warning -Message "Type accelerator '$Name' could not be registered from $($Type.Assembly.GetName().Name): $($_.Exception.Message)"
                            return
                        }

                        $script:PowerForgeRegisteredAssemblyTypeAccelerators[$Name] = $Type
                    }

                    if ($Mode -eq 'Assembly') {
                        foreach ($AssemblyName in $RequestedAssemblies) {
                            $Assembly = & $ImportPowerForgeAlcAssembly -AssemblyName $AssemblyName
                            if ($null -eq $Assembly) {
                                Write-Warning -Message "Assembly '$AssemblyName' was not found in the module AssemblyLoadContext. No type accelerators were registered for it."
                                continue
                            }

                            try {
                                $ExportedTypes = @($Assembly.GetExportedTypes())
                            } catch {
                                Write-Warning -Message "Could not enumerate exported types from assembly '$AssemblyName' for type accelerator exposure: $($_.Exception.Message)"
                                continue
                            }

                            foreach ($Type in $ExportedTypes) {
                                & $AddPowerForgeTypeAccelerator -Type $Type
                            }
                        }
                    }

                    foreach ($TypeName in $RequestedTypes) {
                        $Type = & $FindPowerForgeAlcType -TypeName $TypeName
                        if ($null -eq $Type) {
                            Write-Warning -Message "Type '$TypeName' was not found in the module AssemblyLoadContext. No type accelerator was registered."
                            continue
                        }

                        & $AddPowerForgeTypeAccelerator -Type $Type
                    }

                    if ($script:PowerForgeAssemblyTypeAcceleratorCleanupRegistered -ne $true) {
                        $script:PowerForgeAssemblyTypeAcceleratorCleanupRegistered = $true
                        $PreviousPowerForgeOnRemove = $ExecutionContext.SessionState.Module.OnRemove
                        $ExecutionContext.SessionState.Module.OnRemove = {
                            try {
                                $TypeAccelerators = [psobject].Assembly.GetType('System.Management.Automation.TypeAccelerators')
                                if ($null -eq $TypeAccelerators -or $null -eq $script:PowerForgeRegisteredAssemblyTypeAccelerators) {
                                    return
                                }

                                $GetTypeAccelerators = $TypeAccelerators.GetProperty('Get', [System.Reflection.BindingFlags] 'Static,Public,NonPublic')
                                $RemoveTypeAccelerator = $TypeAccelerators.GetMethod('Remove', [type[]]@([string]))
                                if ($null -eq $GetTypeAccelerators -or $null -eq $RemoveTypeAccelerator) {
                                    return
                                }

                                $Existing = $GetTypeAccelerators.GetValue($null)
                                foreach ($Entry in @($script:PowerForgeRegisteredAssemblyTypeAccelerators.GetEnumerator())) {
                                    if ($Existing.ContainsKey($Entry.Key) -and [object]::ReferenceEquals($Existing[$Entry.Key], $Entry.Value)) {
                                        $RemoveTypeAccelerator.Invoke($null, @($Entry.Key)) | Out-Null
                                    }
                                }
                            } finally {
                                if ($null -ne $PreviousPowerForgeOnRemove) {
                                    & $PreviousPowerForgeOnRemove @args
                                }
                            }
                        }.GetNewClosure()
                    }
                }

                # Type accelerator exposure is PowerShell Core-only because it depends on AssemblyLoadContext.
                try {
                    & $RegisterPowerForgeAssemblyTypeAccelerators -ModuleAssembly $ModuleAssembly -LibFolder $LibFolder
                } catch {
                    Write-Warning -Message "ALC type accelerator registration failed: $($_.Exception.Message)"
                }
                if ($PowerForgeDevelopmentInnerModule) {
                    # Import-Module -Assembly loads the inner binary module into its own module object. PowerShell has no
                    # public API to copy those exported cmdlets back to the script-module wrapper, so this uses the same
                    # private PSModuleInfo hook used by community ALC loaders.
                    $AddExportedCmdlet = [System.Management.Automation.PSModuleInfo].GetMethod(
                        'AddExportedCmdlet',
                        [System.Reflection.BindingFlags]'Instance, NonPublic'
                    )
                    if ($null -ne $AddExportedCmdlet) {
                        foreach ($Cmd in $PowerForgeDevelopmentInnerModule.ExportedCmdlets.Values) {
                            $AddExportedCmdlet.Invoke($ExecutionContext.SessionState.Module, @(, $Cmd)) | Out-Null
                        }
                        $AddExportedAlias = [System.Management.Automation.PSModuleInfo].GetMethod(
                            'AddExportedAlias',
                            [System.Reflection.BindingFlags]'Instance, NonPublic'
                        )
                        if ($null -ne $AddExportedAlias) {
                            foreach ($Alias in $PowerForgeDevelopmentInnerModule.ExportedAliases.Values) {
                                $AliasTarget = if ([string]::IsNullOrWhiteSpace($Alias.Definition)) { $Alias.ResolvedCommandName } else { $Alias.Definition }
                                try {
                                    Set-Alias -Name $Alias.Name -Value $AliasTarget -Scope Local -Force -ErrorAction Stop
                                    $ExportedAlias = $ExecutionContext.SessionState.InvokeCommand.GetCommand($Alias.Name, [System.Management.Automation.CommandTypes]::Alias)
                                    if ($null -ne $ExportedAlias) {
                                        $AddExportedAlias.Invoke($ExecutionContext.SessionState.Module, @(, $ExportedAlias)) | Out-Null
                                    } else {
                                        Write-Warning -Message "Alias '$($Alias.Name)' from DBAClientX.PowerShell was created but could not be resolved for export."
                                    }
                                } catch {
                                    Write-Warning -Message "Alias '$($Alias.Name)' from DBAClientX.PowerShell could not be re-exported: $($_.Exception.Message)"
                                }
                            }
                        } else {
                            Write-Warning -Message "AddExportedAlias is not available on this PowerShell version. Aliases from DBAClientX.PowerShell will not be re-exported to the module scope."
                        }
                    } else {
                        Write-Warning -Message "AddExportedCmdlet is not available on this PowerShell version. Falling back to direct Import-Module; cmdlets from DBAClientX.PowerShell will load from the default context."
                        & $ImportModule $PowerForgeDevelopmentBinaryPath -ErrorAction Stop
                    }
                }
            } else {
                $PowerForgeDevelopmentLoadedType = 'DBAClientX.PowerShell.Initialize' -as [type]
                $PowerForgeDevelopmentLoadedAssembly = if ($PowerForgeDevelopmentLoadedType -and $PowerForgeDevelopmentLoadedType.Assembly) { $PowerForgeDevelopmentLoadedType.Assembly } else { $null }
                $PowerForgeDevelopmentLoadedAssemblyPath = if ($PowerForgeDevelopmentLoadedAssembly -and -not [string]::IsNullOrWhiteSpace($PowerForgeDevelopmentLoadedAssembly.Location)) { [IO.Path]::GetFullPath($PowerForgeDevelopmentLoadedAssembly.Location) } else { $null }
                $PowerForgeDevelopmentSelectedBinaryPath = [IO.Path]::GetFullPath($PowerForgeDevelopmentBinaryPath)
                if ($PowerForgeDevelopmentLoadedAssembly -and [string]::Equals($PowerForgeDevelopmentLoadedAssemblyPath, $PowerForgeDevelopmentSelectedBinaryPath, [StringComparison]::OrdinalIgnoreCase)) {
                    & $ImportModule -Assembly $PowerForgeDevelopmentLoadedType.Assembly -Force -ErrorAction Stop
                } else {
                    & $ImportModule $PowerForgeDevelopmentBinaryPath -ErrorAction Stop
                }
            }
            $PowerForgeDevelopmentBinaryLoaded = $true
        } catch {
            if ($ErrorActionPreference -eq 'Stop') {
                throw
            } else {
                Write-Warning -Message "Importing development binary $PowerForgeDevelopmentBinaryPath failed. Falling back to packaged loader when available. Error: $($_.Exception.Message)"
            }
        }
    }
}

$PowerForgeSourceModuleRoot = [IO.Path]::Combine($PSScriptRoot, 'Module')
$Public = @(Get-ChildItem -Path ([IO.Path]::Combine($PowerForgeSourceModuleRoot, 'Public', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)
$Private = @(Get-ChildItem -Path ([IO.Path]::Combine($PowerForgeSourceModuleRoot, 'Private', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)
$Classes = @(Get-ChildItem -Path ([IO.Path]::Combine($PowerForgeSourceModuleRoot, 'Classes', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)
$Enums = @(Get-ChildItem -Path ([IO.Path]::Combine($PowerForgeSourceModuleRoot, 'Enums', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)

foreach ($Import in @($Classes + $Enums + $Private + $Public)) {
    try {
        . $Import.FullName
    } catch {
        Write-Error -Message "Failed to import function $($Import.FullName): $_"
    }
}

$FunctionsToExport = @()
$CmdletsToExport = @('ConvertTo-DbaXParameterMap', 'Copy-DbaXTableData', 'Get-DbaXMetadata', 'Get-DbaXProviderCapability', 'Get-DbaXSQLiteDiagnostics', 'Get-DbaXSqlServerManagement', 'Get-DbaXSqlServerMonitoring', 'Get-DbaXTableCopyPlan', 'Invoke-DbaXBulkInsert', 'Invoke-DbaXMySql', 'Invoke-DbaXMySqlNonQuery', 'Invoke-DbaXMySqlScalar', 'Invoke-DbaXMySqlTransaction', 'Invoke-DbaXNonQuery', 'Invoke-DbaXOracle', 'Invoke-DbaXOracleNonQuery', 'Invoke-DbaXOracleScalar', 'Invoke-DbaXOracleTransaction', 'Invoke-DbaXPostgreSql', 'Invoke-DbaXPostgreSqlNonQuery', 'Invoke-DbaXPostgreSqlTransaction', 'Invoke-DbaXQuery', 'Invoke-DbaXQueryStream', 'Invoke-DbaXSQLite', 'Invoke-DbaXSQLiteMaintenance', 'Invoke-DbaXSQLiteTransaction', 'Invoke-DbaXStoredProcedure', 'Invoke-DbaXTransaction', 'New-DbaXConnectionString', 'New-DbaXQuery', 'New-DbaXTableCopyDefinition', 'New-DbaXTableCopyPlan', 'Test-DbaXConnection', 'Write-DbaXTableData')
$AliasesToExport = @()
Export-ModuleMember -Function $FunctionsToExport -Alias $AliasesToExport -Cmdlet $CmdletsToExport
