# DbaClientX bootstrapper
# Auto-generated by PowerForge. Do not edit.

$PowerForgeDevelopmentBinaryLoaded = $false
# Source development binary loader
$PowerForgeDevelopmentBinaryRoot = [IO.Path]::GetFullPath([IO.Path]::Combine($PSScriptRoot, '..', 'DbaClientX.PowerShell', 'bin'))
$PowerForgeDevelopmentBinaryMode = 'Environment'
$PowerForgeDevelopmentBinaryEnvironmentVariable = 'DBACLIENTX_USE_DEVELOPMENT_BINARIES'
$PowerForgeDevelopmentConfigurationEnvironmentVariable = 'DBACLIENTX_DEVELOPMENT_CONFIGURATION'
$PowerForgeDevelopmentCoreFrameworks = @('net8.0', 'net472')
$PowerForgeDevelopmentDesktopFrameworks = @('net472', 'net8.0')
$PowerForgeDevelopmentUseAssemblyLoadContext = $true
$PowerForgeDevelopmentEnabled = $false
if ($PowerForgeDevelopmentBinaryMode -eq 'Auto') {
    $PowerForgeDevelopmentEnabled = $true
} elseif ($PowerForgeDevelopmentBinaryMode -eq 'Environment') {
    $PowerForgeDevelopmentRequestedValue = [Environment]::GetEnvironmentVariable($PowerForgeDevelopmentBinaryEnvironmentVariable)
    $PowerForgeDevelopmentEnabled = [string]::Equals($PowerForgeDevelopmentRequestedValue, 'true', [StringComparison]::OrdinalIgnoreCase)
}

if ($PowerForgeDevelopmentEnabled) {
    $PowerForgeDevelopmentConfigurations = @()
    $PowerForgeDevelopmentRequestedConfiguration = [Environment]::GetEnvironmentVariable($PowerForgeDevelopmentConfigurationEnvironmentVariable)
    if (-not [string]::IsNullOrWhiteSpace($PowerForgeDevelopmentRequestedConfiguration)) {
        $PowerForgeDevelopmentConfigurations += $PowerForgeDevelopmentRequestedConfiguration
    }
    $PowerForgeDevelopmentConfigurations += 'Debug'
    $PowerForgeDevelopmentConfigurations += 'Release'
    $PowerForgeDevelopmentConfigurations = @($PowerForgeDevelopmentConfigurations | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)

    $PowerForgeDevelopmentFrameworks = if ($PSEdition -eq 'Core') { $PowerForgeDevelopmentCoreFrameworks } else { $PowerForgeDevelopmentDesktopFrameworks }
    $PowerForgeDevelopmentBinaryPath = $null
    foreach ($PowerForgeDevelopmentConfiguration in $PowerForgeDevelopmentConfigurations) {
        foreach ($PowerForgeDevelopmentFramework in $PowerForgeDevelopmentFrameworks) {
            $PowerForgeDevelopmentCandidate = [IO.Path]::Combine($PowerForgeDevelopmentBinaryRoot, $PowerForgeDevelopmentConfiguration, $PowerForgeDevelopmentFramework, 'DbaClientX.PowerShell.dll')
            if (Test-Path -LiteralPath $PowerForgeDevelopmentCandidate) {
                $PowerForgeDevelopmentBinaryPath = $PowerForgeDevelopmentCandidate
                break
            }
        }
        if ($PowerForgeDevelopmentBinaryPath) { break }
    }

    if ($PowerForgeDevelopmentBinaryPath) {
        try {
            $ImportModule = Get-Command -Name Import-Module -Module Microsoft.PowerShell.Core
            # Ensure native runtime libraries are discoverable for the selected development binary.
            $PowerForgeDevelopmentIsWindowsPlatform = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)
            if ($PowerForgeDevelopmentIsWindowsPlatform) {
                $PowerForgeDevelopmentArch = [System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture
                $PowerForgeDevelopmentArchFolder = switch ($PowerForgeDevelopmentArch) {
                    'X64' { 'win-x64' }
                    'X86' { 'win-x86' }
                    'Arm64' { 'win-arm64' }
                    'Arm' { 'win-arm' }
                    default {
                        Write-Warning -Message ("Unknown Windows architecture '{0}'. Falling back to win-x64 native runtime probing." -f $PowerForgeDevelopmentArch)
                        'win-x64'
                    }
                }
                $PowerForgeDevelopmentLibFolder = [IO.Path]::GetDirectoryName($PowerForgeDevelopmentBinaryPath)
                if ($PowerForgeDevelopmentLibFolder) {
                    $PowerForgeDevelopmentNativePath = Join-Path -Path $PowerForgeDevelopmentLibFolder -ChildPath ("runtimes\{0}\native" -f $PowerForgeDevelopmentArchFolder)
                    $PowerForgeDevelopmentPathEntries = if ([string]::IsNullOrWhiteSpace($env:PATH)) { @() } else { @($env:PATH -split [IO.Path]::PathSeparator) }
                    if ((Test-Path -LiteralPath $PowerForgeDevelopmentNativePath) -and ($PowerForgeDevelopmentPathEntries -notcontains $PowerForgeDevelopmentNativePath)) {
                        if ([string]::IsNullOrWhiteSpace($env:PATH)) {
                            $env:PATH = $PowerForgeDevelopmentNativePath
                        } else {
                            $env:PATH = "$PowerForgeDevelopmentNativePath$([IO.Path]::PathSeparator)$env:PATH"
                        }
                    }
                }
            }
            if ($PSEdition -eq 'Core' -and $PowerForgeDevelopmentUseAssemblyLoadContext) {
                if (-not ('DbaClientX.DevelopmentModuleLoadContext.ModuleAssemblyLoadContext' -as [type])) {
                    Add-Type -TypeDefinition @'
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;

namespace DbaClientX.DevelopmentModuleLoadContext
{
    public sealed class ModuleAssemblyLoadContext : AssemblyLoadContext
    {
        private static readonly object Sync = new object();
        private static readonly Dictionary<string, ModuleAssemblyLoadContext> Contexts = new Dictionary<string, ModuleAssemblyLoadContext>(StringComparer.OrdinalIgnoreCase);

        private readonly string _assemblyDirectory;
        private readonly string _moduleAssemblyPath;
        private readonly AssemblyDependencyResolver _resolver;
        private Assembly _moduleAssembly;

        private ModuleAssemblyLoadContext(string moduleAssemblyPath, string contextName)
            : base(contextName, isCollectible: false)
        {
            _moduleAssemblyPath = Path.GetFullPath(moduleAssemblyPath);
            _assemblyDirectory = Path.GetDirectoryName(_moduleAssemblyPath) ?? string.Empty;
            _resolver = TryCreateResolver(_moduleAssemblyPath);
        }

        public static Assembly LoadModule(string moduleAssemblyPath, string contextName)
        {
            if (string.IsNullOrWhiteSpace(moduleAssemblyPath))
                throw new ArgumentException("Module assembly path is required.", nameof(moduleAssemblyPath));

            var fullPath = Path.GetFullPath(moduleAssemblyPath);
            if (!File.Exists(fullPath))
                throw new FileNotFoundException("Module assembly was not found.", fullPath);

            lock (Sync)
            {
                ModuleAssemblyLoadContext context;
                if (!Contexts.TryGetValue(fullPath, out context))
                {
                    context = new ModuleAssemblyLoadContext(fullPath, string.IsNullOrWhiteSpace(contextName) ? Path.GetFileNameWithoutExtension(fullPath) : contextName);
                    Contexts[fullPath] = context;
                }

                return context.LoadMainModule();
            }
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            if (assemblyName == null || string.IsNullOrWhiteSpace(assemblyName.Name))
                return null;

            var loaderAssembly = typeof(ModuleAssemblyLoadContext).Assembly.GetName();
            if (AssemblyName.ReferenceMatchesDefinition(loaderAssembly, assemblyName))
                return typeof(ModuleAssemblyLoadContext).Assembly;

            var resolvedPath = _resolver?.ResolveAssemblyToPath(assemblyName);
            if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                return LoadFromAssemblyPath(resolvedPath);

            var assemblyPath = Path.Combine(_assemblyDirectory, assemblyName.Name + ".dll");
            return File.Exists(assemblyPath) ? LoadFromAssemblyPath(assemblyPath) : null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            var resolvedPath = _resolver?.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (!string.IsNullOrWhiteSpace(resolvedPath) && File.Exists(resolvedPath))
                return LoadUnmanagedDllFromPath(resolvedPath);

            return IntPtr.Zero;
        }

        private static AssemblyDependencyResolver TryCreateResolver(string assemblyPath)
        {
            try
            {
                return new AssemblyDependencyResolver(assemblyPath);
            }
            catch (InvalidOperationException)
            {
                return null;
            }
        }

        private Assembly LoadMainModule()
        {
            if (_moduleAssembly == null)
                _moduleAssembly = LoadFromAssemblyPath(_moduleAssemblyPath);

            return _moduleAssembly;
        }
    }
}
'@ -Language CSharp -ErrorAction Stop
                }
                $PowerForgeDevelopmentModuleAssembly = [DbaClientX.DevelopmentModuleLoadContext.ModuleAssemblyLoadContext]::LoadModule($PowerForgeDevelopmentBinaryPath, 'DbaClientX.Development')
                $PowerForgeDevelopmentInnerModule = & $ImportModule -Assembly $PowerForgeDevelopmentModuleAssembly -Force -PassThru -ErrorAction Stop
                if ($PowerForgeDevelopmentInnerModule) {
                    # Import-Module -Assembly loads the inner binary module into its own module object. PowerShell has no
                    # public API to copy those exported cmdlets back to the script-module wrapper, so this uses the same
                    # private PSModuleInfo hook used by community ALC loaders.
                    $AddExportedCmdlet = [System.Management.Automation.PSModuleInfo].GetMethod(
                        'AddExportedCmdlet',
                        [System.Reflection.BindingFlags]'Instance, NonPublic'
                    )
                    if ($null -ne $AddExportedCmdlet) {
                        foreach ($Cmd in $PowerForgeDevelopmentInnerModule.ExportedCmdlets.Values) {
                            $AddExportedCmdlet.Invoke($ExecutionContext.SessionState.Module, @(, $Cmd)) | Out-Null
                        }
                        $AddExportedAlias = [System.Management.Automation.PSModuleInfo].GetMethod(
                            'AddExportedAlias',
                            [System.Reflection.BindingFlags]'Instance, NonPublic'
                        )
                        if ($null -ne $AddExportedAlias) {
                            foreach ($Alias in $PowerForgeDevelopmentInnerModule.ExportedAliases.Values) {
                                $AliasTarget = if ([string]::IsNullOrWhiteSpace($Alias.Definition)) { $Alias.ResolvedCommandName } else { $Alias.Definition }
                                try {
                                    Set-Alias -Name $Alias.Name -Value $AliasTarget -Scope Local -Force -ErrorAction Stop
                                    $ExportedAlias = $ExecutionContext.SessionState.InvokeCommand.GetCommand($Alias.Name, [System.Management.Automation.CommandTypes]::Alias)
                                    if ($null -ne $ExportedAlias) {
                                        $AddExportedAlias.Invoke($ExecutionContext.SessionState.Module, @(, $ExportedAlias)) | Out-Null
                                    } else {
                                        Write-Warning -Message "Alias '$($Alias.Name)' from DbaClientX.PowerShell was created but could not be resolved for export."
                                    }
                                } catch {
                                    Write-Warning -Message "Alias '$($Alias.Name)' from DbaClientX.PowerShell could not be re-exported: $($_.Exception.Message)"
                                }
                            }
                        } else {
                            Write-Warning -Message "AddExportedAlias is not available on this PowerShell version. Aliases from DbaClientX.PowerShell will not be re-exported to the module scope."
                        }
                    } else {
                        Write-Warning -Message "AddExportedCmdlet is not available on this PowerShell version. Falling back to direct Import-Module; cmdlets from DbaClientX.PowerShell will load from the default context."
                        & $ImportModule $PowerForgeDevelopmentBinaryPath -ErrorAction Stop
                    }
                }
            } else {
                $PowerForgeDevelopmentLoadedType = 'DbaClientX.PowerShell.Initialize' -as [type]
                $PowerForgeDevelopmentLoadedAssembly = if ($PowerForgeDevelopmentLoadedType -and $PowerForgeDevelopmentLoadedType.Assembly) { $PowerForgeDevelopmentLoadedType.Assembly } else { $null }
                $PowerForgeDevelopmentLoadedAssemblyPath = if ($PowerForgeDevelopmentLoadedAssembly -and -not [string]::IsNullOrWhiteSpace($PowerForgeDevelopmentLoadedAssembly.Location)) { [IO.Path]::GetFullPath($PowerForgeDevelopmentLoadedAssembly.Location) } else { $null }
                $PowerForgeDevelopmentSelectedBinaryPath = [IO.Path]::GetFullPath($PowerForgeDevelopmentBinaryPath)
                if ($PowerForgeDevelopmentLoadedAssembly -and [string]::Equals($PowerForgeDevelopmentLoadedAssemblyPath, $PowerForgeDevelopmentSelectedBinaryPath, [StringComparison]::OrdinalIgnoreCase)) {
                    & $ImportModule -Assembly $PowerForgeDevelopmentLoadedType.Assembly -Force -ErrorAction Stop
                } else {
                    & $ImportModule $PowerForgeDevelopmentBinaryPath -ErrorAction Stop
                }
            }
            $PowerForgeDevelopmentBinaryLoaded = $true
        } catch {
            if ($ErrorActionPreference -eq 'Stop') {
                throw
            } else {
                Write-Warning -Message "Importing development binary $PowerForgeDevelopmentBinaryPath failed. Falling back to packaged loader when available. Error: $($_.Exception.Message)"
            }
        }
    }
}

if (-not $PowerForgeDevelopmentBinaryLoaded) {
    # Get library name, from the PSM1 file name
    $LibraryName = 'DbaClientX.PowerShell'
    $Library = "$LibraryName.dll"
    $Class = "$LibraryName.Initialize"

    $LibRoot = [IO.Path]::Combine($PSScriptRoot, 'Lib')
    $AssemblyFolders = Get-ChildItem -LiteralPath $LibRoot -Directory -ErrorAction SilentlyContinue

    $Default = $false
    $Core = $false
    $Standard = $false
    foreach ($A in $AssemblyFolders.Name) {
        if ($A -eq 'Default') {
            $Default = $true
        } elseif ($A -eq 'Core') {
            $Core = $true
        } elseif ($A -eq 'Standard') {
            $Standard = $true
        }
    }
    if ($Standard -and $Core -and $Default) {
        $FrameworkNet = 'Default'
        $Framework = 'Standard'
    } elseif ($Standard -and $Core) {
        $Framework = 'Standard'
        $FrameworkNet = 'Standard'
    } elseif ($Core -and $Default) {
        $Framework = 'Core'
        $FrameworkNet = 'Default'
    } elseif ($Standard -and $Default) {
        $Framework = 'Standard'
        $FrameworkNet = 'Default'
    } elseif ($Standard) {
        $Framework = 'Standard'
        $FrameworkNet = 'Standard'
    } elseif ($Core) {
        $Framework = 'Core'
        $FrameworkNet = ''
    } elseif ($Default) {
        $Framework = 'Default'
        $FrameworkNet = 'Default'
    } else {
        Write-Error -Message 'No assemblies found'
        return
    }

    if ($PSEdition -eq 'Core') {
        $LibFolder = $Framework
    } else {
        $LibFolder = $FrameworkNet
    }

    # Ensure native runtime libraries are discoverable on Windows
    $IsWindowsPlatform = [System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([System.Runtime.InteropServices.OSPlatform]::Windows)
    # Skip probing when the current host cannot resolve a Windows-facing Lib folder (for example Desktop + Core-only payloads).
    if ($IsWindowsPlatform -and $LibFolder) {
        $Arch = [System.Runtime.InteropServices.RuntimeInformation]::ProcessArchitecture
        # PowerShell switch matches the Architecture enum by its string representation here.
        $ArchFolder = switch ($Arch) {
            'X64' { 'win-x64' }
            'X86' { 'win-x86' }
            'Arm64' { 'win-arm64' }
            'Arm' { 'win-arm' }
            default {
                Write-Warning -Message ("Unknown Windows architecture '{0}'. Falling back to win-x64 native runtime probing." -f $Arch)
                'win-x64'
            }
        }

        $NativePath = Join-Path -Path $PSScriptRoot -ChildPath ("Lib\{0}\runtimes\{1}\native" -f $LibFolder, $ArchFolder)
        $PathEntries = if ([string]::IsNullOrWhiteSpace($env:PATH)) { @() } else { @($env:PATH -split [IO.Path]::PathSeparator) }
        if ((Test-Path -LiteralPath $NativePath) -and ($PathEntries -notcontains $NativePath)) {
            # Prepend the module-native runtime path so the packaged payload wins over unrelated machine-wide copies.
            if ([string]::IsNullOrWhiteSpace($env:PATH)) {
                $env:PATH = $NativePath
            } else {
                $env:PATH = "$NativePath$([IO.Path]::PathSeparator)$env:PATH"
            }
        }
    }
    try {
        $ImportModule = Get-Command -Name Import-Module -Module Microsoft.PowerShell.Core
        $ModuleAssemblyPath = [IO.Path]::Combine($PSScriptRoot, 'Lib', $LibFolder, $Library)

        if ($PSEdition -eq 'Core') {
            $LoaderAssemblyPath = [IO.Path]::Combine($PSScriptRoot, 'Lib', $LibFolder, 'DbaClientX.ModuleLoadContext.dll')
            if (-not ('DbaClientX.ModuleLoadContext.ModuleAssemblyLoadContext' -as [type])) {
                Add-Type -Path $LoaderAssemblyPath -ErrorAction Stop
            }

            $ModuleAssembly = [DbaClientX.ModuleLoadContext.ModuleAssemblyLoadContext]::LoadModule($ModuleAssemblyPath, 'DbaClientX')
            $InnerModule = & $ImportModule -Assembly $ModuleAssembly -Force -PassThru -ErrorAction Stop


            if ($InnerModule) {
                # Import-Module -Assembly loads the inner binary module into its own module object. PowerShell has no
                # public API to copy those exported cmdlets back to the script-module wrapper, so this uses the same
                # private PSModuleInfo hook used by community ALC loaders. This runs on first load and reloads so the
                # outer script module always re-exports cmdlets from the ALC-loaded binary module.
                $AddExportedCmdlet = [System.Management.Automation.PSModuleInfo].GetMethod(
                    'AddExportedCmdlet',
                    [System.Reflection.BindingFlags]'Instance, NonPublic'
                )
                if ($null -ne $AddExportedCmdlet) {
                    foreach ($Cmd in $InnerModule.ExportedCmdlets.Values) {
                        $AddExportedCmdlet.Invoke($ExecutionContext.SessionState.Module, @(, $Cmd)) | Out-Null
                    }
                    $AddExportedAlias = [System.Management.Automation.PSModuleInfo].GetMethod(
                        'AddExportedAlias',
                        [System.Reflection.BindingFlags]'Instance, NonPublic'
                    )
                    if ($null -ne $AddExportedAlias) {
                        foreach ($Alias in $InnerModule.ExportedAliases.Values) {
                            $AliasTarget = if ([string]::IsNullOrWhiteSpace($Alias.Definition)) { $Alias.ResolvedCommandName } else { $Alias.Definition }
                            try {
                                # The alias must exist in this module scope before the private export table can reference it.
                                Set-Alias -Name $Alias.Name -Value $AliasTarget -Scope Local -Force -ErrorAction Stop
                                $ExportedAlias = $ExecutionContext.SessionState.InvokeCommand.GetCommand($Alias.Name, [System.Management.Automation.CommandTypes]::Alias)
                                if ($null -ne $ExportedAlias) {
                                    $AddExportedAlias.Invoke($ExecutionContext.SessionState.Module, @(, $ExportedAlias)) | Out-Null
                                } else {
                                    Write-Warning -Message "Alias '$($Alias.Name)' from $LibraryName was created but could not be resolved for export."
                                }
                            } catch {
                                Write-Warning -Message "Alias '$($Alias.Name)' from $LibraryName could not be re-exported: $($_.Exception.Message)"
                            }
                        }
                    } else {
                        Write-Warning -Message "AddExportedAlias is not available on this PowerShell version. Aliases from $LibraryName will not be re-exported to the module scope."
                    }
                } else {
                    Write-Warning -Message "AddExportedCmdlet is not available on this PowerShell version. Falling back to direct Import-Module; cmdlets from $LibraryName will load from the default context."
                    & $ImportModule $ModuleAssemblyPath -ErrorAction Stop
                }
            }
        } elseif (-not ($Class -as [type])) {
            & $ImportModule $ModuleAssemblyPath -ErrorAction Stop
        } else {
            $Type = "$Class" -as [Type]
            & $ImportModule -Force -Assembly ($Type.Assembly)
        }
    } catch {
        if ($ErrorActionPreference -eq 'Stop') {
            throw
        } else {
            Write-Warning -Message "Importing module $Library failed. Fix errors before continuing. Error: $($_.Exception.Message)"
        }
    }

    if ($PSEdition -ne 'Core') {
        # Core loads dependencies through the module-scoped AssemblyLoadContext above. Dot-sourcing the libraries script
        # there would load dependency DLLs into the default context and undo the isolation this template exists to provide.
        $LibrariesScript = [IO.Path]::Combine($PSScriptRoot, 'DbaClientX.Libraries.ps1')
        if (Test-Path -LiteralPath $LibrariesScript) {
            . $LibrariesScript
        }
    }
}
# Get public and private function definition files.
$Public = @(Get-ChildItem -Path ([IO.Path]::Combine($PSScriptRoot, 'Public', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)
$Private = @(Get-ChildItem -Path ([IO.Path]::Combine($PSScriptRoot, 'Private', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)
$Classes = @(Get-ChildItem -Path ([IO.Path]::Combine($PSScriptRoot, 'Classes', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)
$Enums = @(Get-ChildItem -Path ([IO.Path]::Combine($PSScriptRoot, 'Enums', '*.ps1')) -ErrorAction SilentlyContinue -Recurse)

$FoundErrors = @(
    # Dot source the files (Classes/Enums first).
    foreach ($Import in @($Classes + $Enums + $Private + $Public)) {
        try {
            . $Import.Fullname
        } catch {
            Write-Error -Message "Failed to import functions from $($import.Fullname): $_"
            $true
        }
    }
)

if ($FoundErrors.Count -gt 0) {
    $ModuleName = (Get-ChildItem -Path ([IO.Path]::Combine($PSScriptRoot, '*.psd1'))).BaseName
    Write-Warning "Importing module $ModuleName failed. Fix errors before continuing."
    break
}

$FunctionsToExport = @('Invoke-DbaXMySqlTransaction', 'Invoke-DbaXOracleTransaction', 'Invoke-DbaXPostgreSqlTransaction', 'Invoke-DbaXSQLiteTransaction', 'Invoke-DbaXTransaction')
$CmdletsToExport = @('Copy-DbaXTableData', 'Get-DbaXMetadata', 'Get-DbaXSqlServerManagement', 'Invoke-DbaXMySql', 'Invoke-DbaXMySqlNonQuery', 'Invoke-DbaXMySqlScalar', 'Invoke-DbaXNonQuery', 'Invoke-DbaXOracle', 'Invoke-DbaXOracleNonQuery', 'Invoke-DbaXOracleScalar', 'Invoke-DbaXPostgreSql', 'Invoke-DbaXPostgreSqlNonQuery', 'Invoke-DbaXQuery', 'Invoke-DbaXSQLite', 'New-DbaXQuery', 'Write-DbaXTableData')
$AliasesToExport = @()
Export-ModuleMember -Function $FunctionsToExport -Alias $AliasesToExport -Cmdlet $CmdletsToExport
