using System.Diagnostics;
using DBAClientX;
using DBAClientX.DataMovement;

namespace DBAClientX.PowerShell;

/// <summary>Copies table data from one DbaClientX provider connection to another using paged reads and provider-native bulk writes.</summary>
/// <para>Use this cmdlet for table-to-table imports, exports, and migrations across SQL Server, PostgreSQL, MySQL, Oracle, and SQLite. The reusable copy orchestration lives in DbaClientX.Core while this cmdlet supplies PowerShell-friendly parameters and progress output.</para>
/// <example>
/// <summary>Copy SQLite history rows into SQL Server.</summary>
/// <prefix>PS&gt; </prefix>
/// <code>Copy-DbaXTableData -SourceProvider SQLite -SourceConnectionString 'Data Source=C:\Data\history.db' -SourceTable ProbeResults -DestinationProvider SqlServer -DestinationConnectionString 'Server=.;Database=History;Encrypt=True;TrustServerCertificate=True;Integrated Security=True' -DestinationTable dbo.ProbeResults -OrderBy Id -PageSize 10000 -BatchSize 5000 -ClearDestination -PassThru</code>
/// <para>Reads the SQLite table in deterministic pages and writes each page through SQL Server bulk copy.</para>
/// </example>
/// <example>
/// <summary>Copy between same-shaped staging tables.</summary>
/// <prefix>PS&gt; </prefix>
/// <code>Copy-DbaXTableData -SourceProvider SqlServer -SourceConnectionString $source -SourceTable staging.Customers -DestinationProvider PostgreSql -DestinationConnectionString $dest -DestinationTable public.customers -OrderBy CustomerId -PageSize 25000 -PassThru</code>
/// <para>Copies all rows from SQL Server into PostgreSQL using provider-native read and write paths.</para>
/// </example>
/// <example>
/// <summary>Copy several planned tables.</summary>
/// <prefix>PS&gt; </prefix>
/// <code>$definitions | Copy-DbaXTableData -SourceProvider SQLite -SourceConnectionString $source -DestinationProvider SqlServer -DestinationConnectionString $dest -BatchSize 5000 -PassThru</code>
/// <para>Runs reusable <see cref="DbaTableCopyDefinition"/> objects produced by .NET planning code or constructed directly in PowerShell.</para>
/// </example>
[Cmdlet(VerbsCommon.Copy, "DbaXTableData", SupportsShouldProcess = true)]
[CmdletBinding()]
public sealed class CmdletCopyDbaXTableData : PSCmdlet
{
    private readonly List<DbaTableCopyDefinition> _definitionBuffer = new();
    private ActionPreference _errorAction;

    /// <summary>Provider used to read source rows.</summary>
    [Parameter(Mandatory = true)]
    public DbaXBulkProvider SourceProvider { get; set; }

    /// <summary>Connection string used to read source rows.</summary>
    [Parameter(Mandatory = true)]
    [ValidateNotNullOrEmpty]
    public string SourceConnectionString { get; set; } = string.Empty;

    /// <summary>Source table name. Include schema or owner when required by the provider.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string SourceTable { get; set; } = string.Empty;

    /// <summary>Provider used to write destination rows.</summary>
    [Parameter(Mandatory = true)]
    public DbaXBulkProvider DestinationProvider { get; set; }

    /// <summary>Connection string used to write destination rows.</summary>
    [Parameter(Mandatory = true)]
    [ValidateNotNullOrEmpty]
    public string DestinationConnectionString { get; set; } = string.Empty;

    /// <summary>Destination table name. Include schema or owner when required by the provider.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string DestinationTable { get; set; } = string.Empty;

    /// <summary>Reusable table copy definitions to execute. Use this for multi-table plans generated by DbaClientX.Core.</summary>
    [Parameter(ValueFromPipeline = true)]
    [ValidateNotNullOrEmpty]
    public DbaTableCopyDefinition[]? Definition { get; set; }

    /// <summary>Column names used to order paged source reads. Provide stable key columns for deterministic copies.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? OrderBy { get; set; }

    /// <summary>Allows paged copies without an explicit order. Use only for ad hoc copies where provider natural order is acceptable.</summary>
    [Parameter]
    public SwitchParameter AllowUnordered { get; set; }

    /// <summary>Number of rows read from the source per page.</summary>
    [Parameter]
    public int PageSize { get; set; } = DbaTableCopyOptions.DefaultPageSize;

    /// <summary>Optional number of rows per provider bulk-write batch.</summary>
    [Parameter]
    public int? BatchSize { get; set; }

    /// <summary>Optional provider bulk-copy timeout in seconds. SQLite destinations do not support this option.</summary>
    [Parameter]
    public int? BulkCopyTimeout { get; set; }

    /// <summary>Mapping from source column names to destination column names.</summary>
    [Parameter]
    public Hashtable? ColumnMap { get; set; }

    /// <summary>Source column names excluded from destination pages before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? ExcludeColumn { get; set; }

    /// <summary>Column names converted to Boolean values before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? BooleanColumn { get; set; }

    /// <summary>Column names converted to Int32 values before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? Int32Column { get; set; }

    /// <summary>Column names converted to Int64 values before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? Int64Column { get; set; }

    /// <summary>Column names converted to Decimal values before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? DecimalColumn { get; set; }

    /// <summary>Column names converted to String values before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? StringColumn { get; set; }

    /// <summary>Column names converted to DateTime values before bulk writing.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? DateTimeColumn { get; set; }

    /// <summary>Source key columns used to keep one effective row per key before copying.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? DeduplicateSourceBy { get; set; }

    /// <summary>Source columns used to choose the winning row for each deduplicated source key.</summary>
    [Parameter]
    [ValidateNotNullOrEmpty]
    public string[]? DeduplicateSourceOrderBy { get; set; }

    /// <summary>Uses case-insensitive source keys when deduplicating source rows.</summary>
    [Parameter]
    public SwitchParameter DeduplicateSourceCaseInsensitive { get; set; }

    /// <summary>Treats missing source or destination tables as empty during row counts and clear operations.</summary>
    [Parameter]
    public SwitchParameter TreatMissingTablesAsEmpty { get; set; }

    /// <summary>Allows copying from and to the same provider database table. Use only when intentionally owning the consequences.</summary>
    [Parameter]
    public SwitchParameter AllowSameTableCopy { get; set; }

    /// <summary>Deletes destination table rows before copying source rows.</summary>
    [Parameter]
    public SwitchParameter ClearDestination { get; set; }

    /// <summary>Skips source and destination row-count verification after the copy.</summary>
    [Parameter]
    public SwitchParameter NoVerify { get; set; }

    /// <summary>SQL Server destination option to acquire a bulk update lock for the duration of each bulk copy.</summary>
    [Parameter]
    public SwitchParameter TableLock { get; set; }

    /// <summary>SQL Server destination option to check destination constraints during each bulk copy.</summary>
    [Parameter]
    public SwitchParameter CheckConstraints { get; set; }

    /// <summary>SQL Server destination option to fire insert triggers during each bulk copy.</summary>
    [Parameter]
    public SwitchParameter FireTriggers { get; set; }

    /// <summary>SQL Server destination option to preserve identity values from the source data.</summary>
    [Parameter]
    public SwitchParameter KeepIdentity { get; set; }

    /// <summary>SQL Server destination option to preserve null values from the source data.</summary>
    [Parameter]
    public SwitchParameter KeepNulls { get; set; }

    /// <summary>Writes a result object with copied table counts, verification state, and elapsed time.</summary>
    [Parameter]
    public SwitchParameter PassThru { get; set; }

    /// <inheritdoc />
    protected override void BeginProcessing()
    {
        _errorAction = this.ResolveErrorAction();
    }

    /// <inheritdoc />
    protected override void ProcessRecord()
    {
        if (Definition is { Length: > 0 })
        {
            _definitionBuffer.AddRange(Definition);
        }
    }

    /// <inheritdoc />
    protected override void EndProcessing()
    {
        try
        {
            ValidateOptions();

            var sourceAlias = GetProviderAlias(SourceProvider);
            var destinationAlias = GetProviderAlias(DestinationProvider);
            if (!PowerShellHelpers.TryValidateConnection(
                    this,
                    sourceAlias,
                    SourceConnectionString,
                    _errorAction,
                    allowedUnsupportedOptions: SourceProvider == DbaXBulkProvider.MySql ? PowerShellHelpers.MySqlBulkCopyAllowedUnsupportedOptions : null) ||
                !PowerShellHelpers.TryValidateConnection(
                    this,
                    destinationAlias,
                    DestinationConnectionString,
                    _errorAction,
                    allowedUnsupportedOptions: DestinationProvider == DbaXBulkProvider.MySql ? PowerShellHelpers.MySqlBulkCopyAllowedUnsupportedOptions : null))
            {
                return;
            }

            var definitions = BuildDefinitions();
            var destinationTarget = definitions.Count == 1 ? definitions[0].DestinationName : $"{definitions.Count} table definitions";
            var processMessage = definitions.Count == 1
                ? $"Copy rows from {SourceProvider}:{definitions[0].SourceName} to {DestinationProvider}:{definitions[0].DestinationName}"
                : $"Copy rows from {SourceProvider} to {DestinationProvider} using {definitions.Count} table definitions";
            if (!ShouldProcess(destinationTarget, processMessage))
            {
                return;
            }

            var startedAt = DateTimeOffset.UtcNow;
            var stopwatch = Stopwatch.StartNew();
            var result = CopyAsync(definitions).GetAwaiter().GetResult();
            stopwatch.Stop();

            CompleteProgress();
            if (!result.Verified)
            {
                var message = $"Copy-DbaXTableData verification failed for {destinationTarget}: source rows={result.SourceRows?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "unknown"}, destination rows={result.DestinationRows?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "unknown"}.";
                if (_errorAction == ActionPreference.Stop)
                {
                    throw new PSInvalidOperationException(message);
                }

                WriteWarning(message);
            }

            if (PassThru.IsPresent)
            {
                WriteObject(new PSObject(new
                {
                    SourceProvider,
                    SourceTable = definitions.Count == 1 ? definitions[0].SourceName : null,
                    DestinationProvider,
                    DestinationTable = definitions.Count == 1 ? definitions[0].DestinationName : null,
                    SourceRows = result.SourceRows,
                    CopiedRows = result.CopiedRows,
                    DestinationRows = result.DestinationRows,
                    Verified = result.Verified,
                    Tables = result.Tables,
                    StartedAt = startedAt,
                    CompletedAt = DateTimeOffset.UtcNow,
                    ElapsedMilliseconds = Math.Round(stopwatch.Elapsed.TotalMilliseconds, 2)
                }));
            }
        }
        catch (Exception ex)
        {
            WriteWarning($"Copy-DbaXTableData - Error copying table data: {ex.Message}");
            if (_errorAction == ActionPreference.Stop)
            {
                throw;
            }
        }
    }

    private async Task<DbaTableCopyResult> CopyAsync(IReadOnlyList<DbaTableCopyDefinition> definitions)
    {
        var request = new DbaProviderTableCopyRequest
        {
            Source = new DbaProviderTableCopyAdapterOptions
            {
                Provider = ToTableCopyProvider(SourceProvider),
                ConnectionString = SourceConnectionString,
                DefaultOrderByColumns = OrderBy,
                AllowUnordered = AllowUnordered.IsPresent,
                TreatMissingTablesAsEmpty = TreatMissingTablesAsEmpty.IsPresent
            },
            Destination = new DbaProviderTableCopyAdapterOptions
            {
                Provider = ToTableCopyProvider(DestinationProvider),
                ConnectionString = DestinationConnectionString,
                TreatMissingTablesAsEmpty = TreatMissingTablesAsEmpty.IsPresent
            },
            Definitions = definitions,
            AllowSameProviderTableCopy = AllowSameTableCopy.IsPresent,
            Options = new DbaTableCopyOptions
            {
                PageSize = PageSize,
                BatchSize = BatchSize,
                BulkCopyTimeout = BulkCopyTimeout,
                ClearDestination = ClearDestination.IsPresent,
                VerifyRowCounts = !NoVerify.IsPresent,
                Progress = WriteTableCopyProgress
            }
        };

        return await new DbaProviderTableCopyRunner(
                CreateSourceAdapter,
                CreateDestinationAdapter)
            .CopyAsync(request)
            .ConfigureAwait(false);
    }

    private IDbaTableCopySource CreateSourceAdapter(DbaProviderTableCopyAdapterOptions options)
        => CreateProviderAdapter(options, sqlServerOptions: null);

    private IDbaTableCopyDestination CreateDestinationAdapter(DbaProviderTableCopyAdapterOptions options)
        => CreateProviderAdapter(
            options,
            options.Provider == DbaTableCopyProvider.SqlServer ? BuildSqlServerOptions() : null);

    private static DbaProviderTableCopyAdapterBase CreateProviderAdapter(
        DbaProviderTableCopyAdapterOptions options,
        SqlServerBulkInsertOptions? sqlServerOptions)
        => options.Provider switch
        {
            DbaTableCopyProvider.SqlServer => new SqlServerTableCopyAdapter(options, sqlServerOptions),
            DbaTableCopyProvider.PostgreSql => new PostgreSqlTableCopyAdapter(options),
            DbaTableCopyProvider.MySql => new MySqlTableCopyAdapter(options),
            DbaTableCopyProvider.Oracle => new OracleTableCopyAdapter(options),
            DbaTableCopyProvider.SQLite => new SQLiteTableCopyAdapter(options),
            _ => throw new PSArgumentException($"Provider '{options.Provider}' is not supported.")
        };

    private IReadOnlyList<DbaTableCopyDefinition> BuildDefinitions()
    {
        if (_definitionBuffer.Count > 0)
        {
            foreach (var definition in _definitionBuffer)
            {
                definition.Validate();
            }

            return _definitionBuffer;
        }

        return new[]
        {
            new DbaTableCopyDefinition(
                SourceTable,
                DestinationTable,
                OrderBy,
                DestinationTable,
                ConvertColumnMap(),
                NormalizeExcludedColumnNames(ExcludeColumn),
                BuildColumnTypeConversions(),
                BuildSourceOptions())
        };
    }

    private void ValidateOptions()
    {
        if (PageSize <= 0)
        {
            throw new PSArgumentException("PageSize must be greater than zero.", nameof(PageSize));
        }

        if (BatchSize.HasValue && BatchSize.Value <= 0)
        {
            throw new PSArgumentException("BatchSize must be greater than zero.", nameof(BatchSize));
        }

        if (BulkCopyTimeout.HasValue && BulkCopyTimeout.Value <= 0)
        {
            throw new PSArgumentException("BulkCopyTimeout must be greater than zero.", nameof(BulkCopyTimeout));
        }

        if (DeduplicateSourceOrderBy is { Length: > 0 } && DeduplicateSourceBy is not { Length: > 0 })
        {
            throw new PSArgumentException("DeduplicateSourceBy is required when DeduplicateSourceOrderBy is provided.", nameof(DeduplicateSourceBy));
        }

        var hasDefinitions = Definition is { Length: > 0 } || _definitionBuffer.Count > 0;
        if (!hasDefinitions && string.IsNullOrWhiteSpace(SourceTable))
        {
            throw new PSArgumentException("SourceTable is required unless Definition is provided.", nameof(SourceTable));
        }

        if (!hasDefinitions && string.IsNullOrWhiteSpace(DestinationTable))
        {
            throw new PSArgumentException("DestinationTable is required unless Definition is provided.", nameof(DestinationTable));
        }

        if (DestinationProvider == DbaXBulkProvider.SQLite && BulkCopyTimeout.HasValue)
        {
            throw new PSArgumentException("SQLite bulk inserts do not support BulkCopyTimeout.", nameof(BulkCopyTimeout));
        }

        if (DestinationProvider != DbaXBulkProvider.SqlServer && HasSqlServerOnlyOptions())
        {
            throw new PSArgumentException("TableLock, CheckConstraints, FireTriggers, KeepIdentity, and KeepNulls are only supported for SqlServer destinations.");
        }

        if (!hasDefinitions && (OrderBy == null || OrderBy.Length == 0) && !AllowUnordered.IsPresent)
        {
            throw new PSArgumentException("OrderBy is required for deterministic paged table copy. Use -AllowUnordered for ad hoc copies where natural provider order is acceptable.", nameof(OrderBy));
        }

        if (hasDefinitions && HasSingleTableShapingOptions())
        {
            throw new PSArgumentException("ColumnMap, ExcludeColumn, source deduplication, and type-conversion column switches are only used with SourceTable/DestinationTable. Put per-table shaping on the supplied DbaTableCopyDefinition objects.");
        }

        if (hasDefinitions &&
            !AllowUnordered.IsPresent &&
            (OrderBy == null || OrderBy.Length == 0) &&
            HasUnorderedSuppliedDefinitions())
        {
            throw new PSArgumentException("OrderBy is required when any supplied DbaTableCopyDefinition does not include OrderByColumns. Use -AllowUnordered only for ad hoc copies where provider natural order is acceptable.", nameof(OrderBy));
        }
    }

    private bool HasSqlServerOnlyOptions()
        => TableLock.IsPresent ||
           CheckConstraints.IsPresent ||
           FireTriggers.IsPresent ||
           KeepIdentity.IsPresent ||
           KeepNulls.IsPresent;

    private bool HasSingleTableShapingOptions()
        => ColumnMap is { Count: > 0 } ||
           ExcludeColumn is { Length: > 0 } ||
           BooleanColumn is { Length: > 0 } ||
           Int32Column is { Length: > 0 } ||
           Int64Column is { Length: > 0 } ||
           DecimalColumn is { Length: > 0 } ||
           StringColumn is { Length: > 0 } ||
           DateTimeColumn is { Length: > 0 } ||
           DeduplicateSourceBy is { Length: > 0 } ||
           DeduplicateSourceOrderBy is { Length: > 0 } ||
           DeduplicateSourceCaseInsensitive.IsPresent;

    private bool HasUnorderedSuppliedDefinitions()
        => EnumerateSuppliedDefinitions().Any(static definition => definition.OrderByColumns == null || definition.OrderByColumns.Count == 0);

    private IEnumerable<DbaTableCopyDefinition> EnumerateSuppliedDefinitions()
    {
        if (_definitionBuffer.Count > 0)
        {
            foreach (var definition in _definitionBuffer)
            {
                yield return definition;
            }
        }

        if (Definition == null)
        {
            yield break;
        }

        foreach (var definition in Definition)
        {
            yield return definition;
        }
    }

    private Dictionary<string, string>? ConvertColumnMap()
    {
        if (ColumnMap is not { Count: > 0 })
        {
            return null;
        }

        var mappings = new Dictionary<string, string>(PowerShellHelpers.GetHashtableComparer(ColumnMap));
        foreach (DictionaryEntry entry in ColumnMap)
        {
            var source = entry.Key?.ToString();
            var destination = entry.Value?.ToString();
            if (string.IsNullOrWhiteSpace(source))
            {
                throw new PSArgumentException("ColumnMap source column names cannot be null or whitespace.", nameof(ColumnMap));
            }

            if (string.IsNullOrWhiteSpace(destination))
            {
                throw new PSArgumentException("ColumnMap destination column names cannot be null or whitespace.", nameof(ColumnMap));
            }

            mappings[source!] = destination!;
        }

        return mappings;
    }

    private static IReadOnlyList<string>? NormalizeColumnNames(string[]? columns)
    {
        var normalized = columns?
            .Where(static column => !string.IsNullOrWhiteSpace(column))
            .Select(static column => column.Trim())
            .ToArray();
        return normalized is { Length: > 0 } ? normalized : null;
    }

    private static IReadOnlyCollection<string>? NormalizeExcludedColumnNames(string[]? columns)
    {
        var normalized = columns?
            .Where(static column => !string.IsNullOrWhiteSpace(column))
            .Select(static column => column.Trim())
            .ToArray();
        return normalized is { Length: > 0 }
            ? new HashSet<string>(normalized, StringComparer.OrdinalIgnoreCase)
            : null;
    }

    private Dictionary<string, DbaTableCopyColumnType>? BuildColumnTypeConversions()
    {
        var conversions = new Dictionary<string, DbaTableCopyColumnType>(StringComparer.OrdinalIgnoreCase);
        AddColumnTypeConversions(conversions, BooleanColumn, DbaTableCopyColumnType.Boolean);
        AddColumnTypeConversions(conversions, Int32Column, DbaTableCopyColumnType.Int32);
        AddColumnTypeConversions(conversions, Int64Column, DbaTableCopyColumnType.Int64);
        AddColumnTypeConversions(conversions, DecimalColumn, DbaTableCopyColumnType.Decimal);
        AddColumnTypeConversions(conversions, StringColumn, DbaTableCopyColumnType.String);
        AddColumnTypeConversions(conversions, DateTimeColumn, DbaTableCopyColumnType.DateTime);
        return conversions.Count == 0 ? null : conversions;
    }

    private DbaTableCopySourceOptions? BuildSourceOptions()
    {
        var deduplicateBy = NormalizeColumnNames(DeduplicateSourceBy);
        if (deduplicateBy == null)
        {
            return null;
        }

        return new DbaTableCopySourceOptions(
            deduplicateBy.ToArray(),
            NormalizeColumnNames(DeduplicateSourceOrderBy)?.ToArray(),
            DeduplicateSourceCaseInsensitive.IsPresent);
    }

    private static void AddColumnTypeConversions(
        IDictionary<string, DbaTableCopyColumnType> conversions,
        IEnumerable<string>? columns,
        DbaTableCopyColumnType conversion)
    {
        if (columns == null)
        {
            return;
        }

        foreach (var column in columns.Where(static column => !string.IsNullOrWhiteSpace(column)))
        {
            conversions[column.Trim()] = conversion;
        }
    }

    private SqlServerBulkInsertOptions? BuildSqlServerOptions()
    {
        if (DestinationProvider != DbaXBulkProvider.SqlServer || !HasSqlServerOnlyOptions())
        {
            return null;
        }

        return SqlServerBulkInsertOptionFactory.Create(
            TableLock.IsPresent,
            CheckConstraints.IsPresent,
            FireTriggers.IsPresent,
            KeepIdentity.IsPresent,
            KeepNulls.IsPresent,
            autoCreateTable: false);
    }

    private void WriteTableCopyProgress(DbaTableCopyProgress progress)
    {
        var record = new ProgressRecord(2, $"Copying {progress.TableName}", $"{progress.RowsCopied} row(s) copied")
        {
            PercentComplete = progress.PercentComplete.HasValue
                ? Math.Min(100, (int)Math.Round(progress.PercentComplete.Value))
                : -1
        };

        WriteProgress(record);
    }

    private void CompleteProgress()
    {
        WriteProgress(new ProgressRecord(2, "Copying table data", "Complete")
        {
            RecordType = ProgressRecordType.Completed
        });
    }

    private static DbaTableCopyProvider ToTableCopyProvider(DbaXBulkProvider provider)
        => provider switch
        {
            DbaXBulkProvider.SqlServer => DbaTableCopyProvider.SqlServer,
            DbaXBulkProvider.PostgreSql => DbaTableCopyProvider.PostgreSql,
            DbaXBulkProvider.MySql => DbaTableCopyProvider.MySql,
            DbaXBulkProvider.Oracle => DbaTableCopyProvider.Oracle,
            DbaXBulkProvider.SQLite => DbaTableCopyProvider.SQLite,
            _ => throw new PSArgumentException($"Provider '{provider}' is not supported.")
        };

    private static string GetProviderAlias(DbaXBulkProvider provider)
        => provider switch
        {
            DbaXBulkProvider.SqlServer => "sqlserver",
            DbaXBulkProvider.PostgreSql => "postgresql",
            DbaXBulkProvider.MySql => "mysql",
            DbaXBulkProvider.Oracle => "oracle",
            DbaXBulkProvider.SQLite => "sqlite",
            _ => throw new PSArgumentException($"Provider '{provider}' is not supported.")
        };
}
